version: "3"
services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app/server
    command: 'python server/manage.py runserver'
    env_file:
      - ./.env.local