version: "3"
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - /home/sodiqit/backups/news_blog:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_NAME}"
  backend:
    depends_on: [db]
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    command: 'python -u server/manage.py runserver 0.0.0.0:8000'
    env_file:
      - ./.env.local