# Generated by Django 4.0.5 on 2022-08-30 10:37

import app.apps.posts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(
                    upload_to=app.apps.posts.models.get_post_photos_upload_path)),
                ('post', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.CASCADE, related_name='post', to='posts.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posts.postimage'),
        ),
    ]
