# Generated by Django 4.0.5 on 2022-08-30 10:39

import app.apps.posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_preview_postimage_post_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=app.apps.posts.models.get_preview_upload_path),
        ),
    ]
