# Generated by Django 4.0.5 on 2022-09-01 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_author'),
        ('posts', '0007_remove_post_images_alter_postimage_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.author'),
        ),
        migrations.CreateModel(
            name='PostDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moderate_status', models.TextField(choices=[('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('PENDING', 'Pending'), ('NEED_CHANGES', 'Need Changes')])),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='posts.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='posts.postdraft'),
        ),
    ]
