# Generated by Django 4.0.5 on 2022-09-02 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_author_postdraft_post_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdraft',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='draft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='posts.postdraft'),
        ),
    ]
